# Site settings
title: nightmare.website
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nightmare.website" # the base hostname & protocol for your site

paginate: 4
paginate_path: "/blog/page:num/"

permalink: /blog/:title

highlighter: pygments

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
